window.CUSTOM_APP_CONFIG = {
  appTitle: "Mon Qua Nho",
  appIcon: "assets/images/icons/couple.png",
  enableWebsiteInfo: true,
  enablePasscode: false,
  enableMorphEffect: true,
  enableSphere: true,
  enableSphereFlyingImages: true,
  enableMeteorShower: true,
  enableLetter: true,
  passcode: "0308",
  passcodeTitle: "Nhap mat khau",
  passcodeSubtitle: "Mo mon qua dac biet",
  morphTexts: ["Happy birth day", "Minh Anh", "Tuổi mới rực rỡ"],
  particleImage: "image/p1.jpg",
  sphereImages: [
    "image/p1.jpg",
    "image/p3.jpg",
    "image/p4.jpg",
    "image/p5.jpg",
    "image/p6.jpg",
    "image/p7.jpg",
    "image/p8.jpg",
    "image/p9.jpg",
    "image/p10.jpg",
    "image/p11.jpg",
    "image/p12.jpg",
    "image/p13.jpg",
    "image/p14.jpg",
    "image/p15.jpg",
    "image/p16.jpg",
    "image/p17.jpg",
    "image/p18.jpg",
    "image/p19.jpg",
    "image/p20.jpg",
    "image/p21.jpg",
    "image/p22.jpg",
    "image/p23.jpg",
    "image/p24.jpg",
    "image/p25.jpg",
    "image/p26.jpg",
    "image/p27.jpg",
    "image/p28.jpg",
    "image/p29.jpg",
    "image/p30.jpg",
    "image/p31.jpg",
    "image/p32.jpg",
    "image/p33.jpg",
  ],
  burstWishTexts: [
    "Mừng sinh nhật Anh nhé",
    "Hữu duyên ngày càng xinh đẹp",
    "Ráng lấy bằng lái xe nha",
    "Có lương nhớ rủ đi nhậu",
  ],
  letter: {
    text: "Chúc mừng sinh nhật Minh Anh nhé! Hôm nay là ngày đặc biệt nên Phú muốn gửi đến Anh thật nhiều lời chúc tốt đẹp nhất. Chúc Anh luôn xinh đẹp, vui vẻ và lúc nào cũng tràn đầy năng lượng tích cực. Mong rằng mọi ước mơ của Anh đều sẽ dần trở thành hiện thực và con đường phía trước luôn gặp nhiều may mắn. Cảm ơn bạn vì đã luôn là một người con xóm buồn đáng quý. Chúc tuổi mới của Anh thật rực rỡ và hạnh phúc!",
    image: "image/p31.jpg",
    caption: "❤💕💖",
  },
  bgMusic: "music/music.mp3",
  bgVolume: 0.55,
  assetVersion: "",
};
